#dirs to store config files from server
homePath:
  - /Users/liolay/haha
#server to fetch config files
server: localhost:5337
#server to fetch config files
tick: 5
#fetch config
apps:
  - name: app01-name   #app
    profile: default   #profile
    label: master      #git branch name or commit id
    rootPath:          #store path
      - /Users/liolay
  - name: app-name
    profile: default
    label: master
    rootPath:
      - /Users/liolay
      - /Users/liolay1

